Pass top-level verilog parameters to synthesis; report power, core area and critical path in generated reports
The-OpenROAD-Project/OpenLane pull request #1105
Opened 2022-05-23 22:08 UTC by growly

1) Defining `$::env(SYNTH_PARAMETERS)` passes top-level verilog module parameters to the yosys synth script, so you can override them per run.
2) Core area, various post-parasitics power numbers and critical path are all extracted for the automatic reports `generate_reports.py` creates. I wonder if these should be hidden behind an option like `MORE_METRICS`?

2022-05-24 15:00 UTC, donn approved these changes
Looks OK

2022-05-24 15:02 UTC, donn requested changes
Wait, wait. Can you please document the new option you've added?

2022-05-25 17:26 UTC, donn commented
I meant the `SYNTH_PARAMETERS` variable, but that I forgot about that file, so thank you for that. I went ahead and added SYNTH_PARAMETERS myself.

2022-05-25 17:27 UTC, merged

2022-06-10 13:47 UTC, proppy commented on scripts/report/report.py
> +                            "total": float(match[4]),
was that deliberate to not add this to the csv?

/cc @growly