Fix loading design configs again
The-OpenROAD-Project/OpenLane pull request #1626
Opened 2023-01-16 17:57 UTC by kareefardi

+ Raise exception when path in allowed trees not found
+ Raise exception when a path outside allowed trees is provided. In the docs, these are allowed but globs are not parsed for example. Please advice if this is a desirable change. 

~ wrap section that parses each variable in try and catch so that the exception message contains both key and value. Previously, some exceptions thrown due to value errors were captured at the main function scope and hence losing the ability to find at which key the exception occurred. This is not a mandatory change and can be removed if not desirable.

2023-01-16 21:31 UTC, donn commented
I must admit I don't entirely see the value in reporting a failed glob as an exception. Why not just print a warning?

2023-01-16 21:33 UTC, donn commented on scripts/config/tcl.py
> +                    raise InvalidConfig(f"Invalid path: {full_abspath}")
That's not an invalid path... That's literally any path that would ascend from the PDK or SCL.

2023-01-16 21:35 UTC, donn approved these changes

2023-01-16 21:35 UTC, donn commented on scripts/config/tcl.py
> +                        raise InvalidConfig(f"No such file {full_abspath}")
Warning?

2023-01-16 21:37 UTC, donn requested changes

2023-01-16 21:37 UTC, donn commented on scripts/config/tcl.py
> +                    raise InvalidConfig(f"Invalid path: {full_abspath}")
Not an invalid path, that's every path that would ascend...

2023-01-16 21:37 UTC, donn commented on scripts/config/tcl.py
> +                        raise InvalidConfig(f"No such file {full_abspath}")
Why not just a warning? The glob thing is best-effort. It shouldn't stop the whole flow. Maybe the user wants the path for something else down the line, i.e., it's going to be used by a later step. Let's not be presumptuous.

2023-01-16 22:01 UTC, kareefardi commented
Makes sense. How about this: if a glob doesn't match, keep the `*`, warn the user and continue?

2023-01-17 22:56 UTC, kareefardi commented
@donn I found out that there is no current mechanism for tcl.py (and others) to report warnings and I thought that there isn't much added value for a warning. This will simply only resolve the ref in case of failed glob. I believe other parts in the flow can capture "wrong" file path

2023-01-18 15:00 UTC, donn approved these changes

2023-01-18 15:03 UTC, donn approved these changes
lgtm

2023-01-18 15:03 UTC, merged