or: update boost version
The-OpenROAD-Project/OpenLane pull request #1666
Opened 2023-02-22 06:03 UTC by vvbandeira

OpenROAD requires min 1.78. Changing to 1.80 since is newer and tested upstream.

2023-02-22 09:44 UTC, donn requested changes
Please also update OpenROAD 's revision so the build is actually tested- the Dockerfile is not run if the version is otherwise unchanged

2023-02-27 11:42 UTC, vvbandeira commented
@donn, any ideas/suggestions on the CI failure?

2023-03-01 16:19 UTC, maliberty commented
@donn this is preventing an testing of OL in the OR CI.  Please help get this resolved so we can resume testing.  Thanks.

2023-03-04 15:07 UTC, maliberty commented
I tried re-running the 
![image](https://user-images.githubusercontent.com/761514/222913574-c2fe75c2-b224-4780-9f14-8e0ef91add69.png)
 action but it fails with 
![image](https://user-images.githubusercontent.com/761514/222913580-72df95f6-ed81-4f5e-9fc5-db31cea2f7e0.png)

I think it is just timing out.  Is this platform much slower than the others?

2023-03-04 15:10 UTC, maliberty commented
Building all the dependencies from scratch isn't great.  It would be better to cache them in a docker image or some other mechanism.

2023-03-05 09:12 UTC, donn commented
@maliberty Has nothing to do with the dependencies per se. OpenROAD compiling on ARM just takes forever because of ABC.

What I usually do is boot up a VM and push the image manually.

2023-03-05 10:10 UTC, donn commented
Build runs into https://github.com/The-OpenROAD-Project/OpenROAD/issues/2833

```
/opt/rh/devtoolset-8/root/usr/bin/ar qc libabc.a CMakeFiles/libabc.dir/src/base/abc/abcAig.c.o CMakeFiles/libabc.dir/src/base/abc/abcBarBuf.c.o CMakeFiles/libabc.dir/src/base/abc/abcBlifMv.c.o CMakeFiles/libabc.dir/src/base/abc/abcCheck.c.o CMakeFiles/libabc.dir/src/base/abc/abcDfs.c.o CMakeFiles/libabc.dir/src/base/abc/abcFanio.c.o CMakeFiles/libabc.dir/src/base/abc/abcFanOrder.c.o CMakeFiles/libabc.dir/src/base/abc/abcFunc.c.o CMakeFiles/libabc.dir/src/base/abc/abcHie.c.o CMakeFiles/libabc.dir/src/base/abc/abcHieCec.c.o CMakeFiles/libabc.dir/src/base/abc/abcHieGia.c.o CMakeFiles/libabc.dir/src/base/abc/abcHieNew.c.o CMakeFiles/libabc.dir/src/base/abc/abcLatch.c.o CMakeFiles/libabc.dir/src/base/abc/abcLib.c.o CMakeFiles/libabc.dir/src/base/abc/abcMinBase.c.o CMakeFiles/libabc.dir/src/base/abc/abcNames.c.o CMakeFiles/libabc.dir/src/base/abc/abcNetlist.c.o CMakeFiles/libabc.dir/src/base/abc/abcNtk.c.o CMakeFiles/libabc.dir/src/base/abc/abcObj.c.o CMakeFiles/libabc.dir/src/base/abc/abcRefs.c.o CMakeFiles/libabc.dir/src/base/abc/abcShow.c.o CMakeFiles/libabc.dir/src/base/abc/abcSop.c.o CMakeFiles/libabc.dir/src/base/abc/abcUtil.c.o CMakeFiles/libabc.dir/src/base/abci/abc.c.o CMakeFiles/libabc.dir/src/base/abci/abcAttach.c.o CMakeFiles/libabc.dir/src/base/abci/abcAuto.c.o CMakeFiles/libabc.dir/src/base/abci/abcBalance.c.o CMakeFiles/libabc.dir/src/base/abci/abcBidec.c.o CMakeFiles/libabc.dir/src/base/abci/abcBm.c.o CMakeFiles/libabc.dir/src/base/abci/abcBmc.c.o CMakeFiles/libabc.dir/src/base/abci/abcCas.c.o CMakeFiles/libabc.dir/src/base/abci/abcCascade.c.o CMakeFiles/libabc.dir/src/base/abci/abcCollapse.c.o CMakeFiles/libabc.dir/src/base/abci/abcCut.c.o CMakeFiles/libabc.dir/src/base/abci/abcDar.c.o CMakeFiles/libabc.dir/src/base/abci/abcDebug.c.o CMakeFiles/libabc.dir/src/base/abci/abcDec.c.o CMakeFiles/libabc.dir/src/base/abci/abcDetect.c.o CMakeFiles/libabc.dir/src/base/abci/abcDress.c.o CMakeFiles/libabc.dir/src/base/abci/abcDress2.c.o CMakeFiles/libabc.dir/src/base/abci/abcDress3.c.o CMakeFiles/libabc.dir/src/base/abci/abcDsd.c.o CMakeFiles/libabc.dir/src/base/abci/abcEco.c.o CMakeFiles/libabc.dir/src/base/abci/abcExact.c.o CMakeFiles/libabc.dir/src/base/abci/abcExtract.c.o CMakeFiles/libabc.dir/src/base/abci/abcFraig.c.o CMakeFiles/libabc.dir/src/base/abci/abcFx.c.o CMakeFiles/libabc.dir/src/base/abci/abcFxu.c.o CMakeFiles/libabc.dir/src/base/abci/abcGen.c.o CMakeFiles/libabc.dir/src/base/abci/abcHaig.c.o CMakeFiles/libabc.dir/src/base/abci/abcIf.c.o CMakeFiles/libabc.dir/src/base/abci/abcIfif.c.o CMakeFiles/libabc.dir/src/base/abci/abcIfMux.c.o CMakeFiles/libabc.dir/src/base/abci/abcIvy.c.o CMakeFiles/libabc.dir/src/base/abci/abcLog.c.o CMakeFiles/libabc.dir/src/base/abci/abcLut.c.o CMakeFiles/libabc.dir/src/base/abci/abcLutmin.c.o CMakeFiles/libabc.dir/src/base/abci/abcMap.c.o CMakeFiles/libabc.dir/src/base/abci/abcMerge.c.o CMakeFiles/libabc.dir/src/base/abci/abcMfs.c.o CMakeFiles/libabc.dir/src/base/abci/abcMini.c.o CMakeFiles/libabc.dir/src/base/abci/abcMiter.c.o CMakeFiles/libabc.dir/src/base/abci/abcMulti.c.o CMakeFiles/libabc.dir/src/base/abci/abcNtbdd.c.o CMakeFiles/libabc.dir/src/base/abci/abcNpn.c.o CMakeFiles/libabc.dir/src/base/abci/abcNpnSave.c.o CMakeFiles/libabc.dir/src/base/abci/abcOdc.c.o CMakeFiles/libabc.dir/src/base/abci/abcOrder.c.o CMakeFiles/libabc.dir/src/base/abci/abcPart.c.o CMakeFiles/libabc.dir/src/base/abci/abcPrint.c.o CMakeFiles/libabc.dir/src/base/abci/abcProve.c.o CMakeFiles/libabc.dir/src/base/abci/abcQbf.c.o CMakeFiles/libabc.dir/src/base/abci/abcQuant.c.o CMakeFiles/libabc.dir/src/base/abci/abcRec3.c.o CMakeFiles/libabc.dir/src/base/abci/abcReconv.c.o CMakeFiles/libabc.dir/src/base/abci/abcReach.c.o CMakeFiles/libabc.dir/src/base/abci/abcRefactor.c.o CMakeFiles/libabc.dir/src/base/abci/abcRenode.c.o CMakeFiles/libabc.dir/src/base/abci/abcReorder.c.o CMakeFiles/libabc.dir/src/base/abci/abcRestruct.c.o CMakeFiles/libabc.dir/src/base/abci/abcResub.c.o CMakeFiles/libabc.dir/src/base/abci/abcRewrite.c.o CMakeFiles/libabc.dir/src/base/abci/abcRpo.c.o CMakeFiles/libabc.dir/src/base/abci/abcRr.c.o CMakeFiles/libabc.dir/src/base/abci/abcRunGen.c.o CMakeFiles/libabc.dir/src/base/abci/abcSat.c.o CMakeFiles/libabc.dir/src/base/abci/abcSaucy.c.o CMakeFiles/libabc.dir/src/base/abci/abcScorr.c.o CMakeFiles/libabc.dir/src/base/abci/abcSense.c.o CMakeFiles/libabc.dir/src/base/abci/abcSpeedup.c.o CMakeFiles/libabc.dir/src/base/abci/abcStrash.c.o CMakeFiles/libabc.dir/src/base/abci/abcSweep.c.o CMakeFiles/libabc.dir/src/base/abci/abcSymm.c.o CMakeFiles/libabc.dir/src/base/abci/abcTim.c.o CMakeFiles/libabc.dir/src/base/abci/abcTiming.c.o CMakeFiles/libabc.dir/src/base/abci/abcUnate.c.o CMakeFiles/libabc.dir/src/base/abci/abcUnreach.c.o CMakeFiles/libabc.dir/src/base/abci/abcVerify.c.o CMakeFiles/libabc.dir/src/base/abci/abcXsim.c.o CMakeFiles/libabc.dir/src/base/cmd/cmd.c.o CMakeFiles/libabc.dir/src/base/cmd/cmdAlias.c.o CMakeFiles/libabc.dir/src/base/cmd/cmdApi.c.o CMakeFiles/libabc.dir/src/base/cmd/cmdAuto.c.o CMakeFiles/libabc.dir/src/base/cmd/cmdFlag.c.o CMakeFiles/libabc.dir/src/base/cmd/cmdHist.c.o CMakeFiles/libabc.dir/src/base/cmd/cmdLoad.c.o CMakeFiles/libabc.dir/src/base/cmd/cmdPlugin.c.o CMakeFiles/libabc.dir/src/base/cmd/cmdStarter.c.o CMakeFiles/libabc.dir/src/base/cmd/cmdUtils.c.o CMakeFiles/libabc.dir/src/base/io/io.c.o CMakeFiles/libabc.dir/src/base/io/ioJson.c.o CMakeFiles/libabc.dir/src/base/io/ioReadAiger.c.o CMakeFiles/libabc.dir/src/base/io/ioReadBaf.c.o CMakeFiles/libabc.dir/src/base/io/ioReadBblif.c.o CMakeFiles/libabc.dir/src/base/io/ioReadBench.c.o CMakeFiles/libabc.dir/src/base/io/ioReadBlif.c.o CMakeFiles/libabc.dir/src/base/io/ioReadBlifAig.c.o CMakeFiles/libabc.dir/src/base/io/ioReadBlifMv.c.o CMakeFiles/libabc.dir/src/base/io/ioReadDsd.c.o CMakeFiles/libabc.dir/src/base/io/ioReadEdif.c.o CMakeFiles/libabc.dir/src/base/io/ioReadEqn.c.o CMakeFiles/libabc.dir/src/base/io/ioReadPla.c.o CMakeFiles/libabc.dir/src/base/io/ioReadPlaMo.c.o CMakeFiles/libabc.dir/src/base/io/ioReadVerilog.c.o CMakeFiles/libabc.dir/src/base/io/ioUtil.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteAiger.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteBaf.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteBblif.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteBench.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteBlif.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteBlifMv.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteBook.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteCnf.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteDot.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteEqn.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteGml.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteList.c.o CMakeFiles/libabc.dir/src/base/io/ioWritePla.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteVerilog.c.o CMakeFiles/libabc.dir/src/base/io/ioWriteSmv.c.o CMakeFiles/libabc.dir/src/base/main/mainFrame.c.o CMakeFiles/libabc.dir/src/base/main/mainInit.c.o CMakeFiles/libabc.dir/src/base/main/mainLib.c.o CMakeFiles/libabc.dir/src/base/main/mainReal.c.o CMakeFiles/libabc.dir/src/base/main/libSupport.c.o CMakeFiles/libabc.dir/src/base/main/mainUtils.c.o CMakeFiles/libabc.dir/src/base/exor/exor.c.o CMakeFiles/libabc.dir/src/base/exor/exorBits.c.o CMakeFiles/libabc.dir/src/base/exor/exorCubes.c.o CMakeFiles/libabc.dir/src/base/exor/exorLink.c.o CMakeFiles/libabc.dir/src/base/exor/exorList.c.o CMakeFiles/libabc.dir/src/base/exor/exorUtil.c.o CMakeFiles/libabc.dir/src/base/ver/verCore.c.o CMakeFiles/libabc.dir/src/base/ver/verFormula.c.o CMakeFiles/libabc.dir/src/base/ver/verParse.c.o CMakeFiles/libabc.dir/src/base/ver/verStream.c.o CMakeFiles/libabc.dir/src/base/wlc/wlcAbs.c.o CMakeFiles/libabc.dir/src/base/wlc/wlcAbs2.c.o CMakeFiles/libabc.dir/src/base/wlc/wlcAbc.c.o CMakeFiles/libabc.dir/src/base/wlc/wlcPth.c.o CMakeFiles/libabc.dir/src/base/wlc/wlcBlast.c.o CMakeFiles/libabc.dir/src/base/wlc/wlcCom.c.o CMakeFiles/libab [...]

2023-03-05 15:27 UTC, maliberty commented
@donn there have been no changes to abc afaik.  Why is this an issue now?  It seems orthogonal to this update.

2023-03-05 18:03 UTC, kareefardi commented
@maliberty I am getting an error with https://github.com/The-OpenROAD-Project/OpenROAD/blob/6de104daffe029fd717645b21f3e6ed6aad1042b/src/par/CMakeLists.txt#L39. `-m64` is not available for arm64

2023-03-07 11:37 UTC, donn approved these changes
Fixed with a `sed` patch

2023-03-07 12:08 UTC, merged