Linter(Verilator) enhancements
The-OpenROAD-Project/OpenLane pull request #1837
Opened 2023-06-06 15:34 UTC by kareefardi

```
rename verilator variables:
QUIT_ON_VERILATOR_ERRORS -> QUIT_ON_LINTER_ERRORS
QUIT_ON_VERILATOR_WARNINGS -> QUIT_ON_LINTER_WARNINGS
VERILATOR_RELATIVE_INCLUDES -> LINTER_RELATIVE_INCLUDES
RUN_VERILATOR -> RUN_LINTER
add LINTER_INCLUDE_PDK_MODELS
add LINTER_DEFINES
add LINTER_TIMING_CONSTRUCTS
```

2023-06-08 14:36 UTC, kareefardi commented
TODO: remove LINTER_TIMING_CONSTRUCTS and disallow them

2023-06-18 10:54 UTC, donn approved these changes
let me state for the record that i hate this

2023-06-18 10:55 UTC, donn requested changes

2023-06-18 10:55 UTC, donn commented on scripts/tcl_commands/synthesis.tcl
> +            puts_err "$errors_count errors found by then Linter"
`then Linter` -> `linter`

2023-06-18 14:39 UTC, donn approved these changes

2023-06-19 07:30 UTC, donn approved these changes

2023-06-19 08:47 UTC, merged