Deprecate `-overwrite` and `-gui`
The-OpenROAD-Project/OpenLane pull request #1840
Opened 2023-06-07 17:34 UTC by kareefardi

`-gui` is superseded by `gui.py`. `or_gui` should still work for interactive scripts. `-overwrite` has no value since support for resuming the flow is dropped.

2023-06-07 17:38 UTC, mguthaus commented
Dropping -overwrite requires that a user manually delete a run directory every time they want to re-run with a tag. otherwise, the run will continue starting with the last step of the previous run. I believe this wll result in quite a bit of user confusion.

Suggestion: 
Either keep -overwrite or fail if a run directory of a given tag already exists.

2023-06-07 17:40 UTC, mguthaus commented
Defaulting to overwrite without warning could be catastrophic, and is not recommended.

2023-06-07 17:55 UTC, kareefardi commented
I wanted to drop support for rerunning existing tag, but I guess I can do that while requiring `-overwrite` to re-use a tag.

2023-06-13 11:41 UTC, donn requested changes

2023-06-13 11:41 UTC, donn commented on flow.tcl
>          return
Exit should be non-zero.

2023-06-13 22:22 UTC, donn approved these changes

2023-06-14 09:05 UTC, merged