Bring mergeLibs.pl from ORFS to OL to handle multiple Liberty files i…
The-OpenROAD-Project/OpenLane pull request #872
Opened 2022-01-19 22:31 UTC by maliberty

…n yosys

Required to make asap7 work as it uses multiple .libs unlike skywater*

Signed-off-by: Matt Liberty <mliberty@eng.ucsd.edu>

2022-01-19 23:48 UTC, arlpetergadfort commented
Why not just use the yosys interface with abc to send in all the lib? It's supported by yosys so there is no need to merge lib files

2022-01-20 00:12 UTC, donn requested changes
mergeLib.pl needs a copyright header

2022-01-20 00:36 UTC, mithro commented
Didn't we just get rid of all the Perl files?

2022-01-20 00:59 UTC, donn commented
Yeah, I'm not sure if asking for a python rewrite is a bridge too far though

2022-01-20 03:55 UTC, maliberty commented
> Why not just use the yosys interface with abc to send in all the lib? It's supported by yosys so there is no need to merge lib files

@arlpetergadfort  I'm glad to abandon this PR if there is a better solution.  What specifically are you suggesting?

2022-01-20 03:56 UTC, maliberty commented
> Yeah, I'm not sure if asking for a python rewrite is a bridge too far though

IMO, I don't think the language matters much - it is a simple script that wouldn't be any better in python.

2022-01-20 09:01 UTC, donn commented
Just for maintainability reasons. The less languages the better.

2022-01-20 13:17 UTC, arlpetergadfort commented
> > Why not just use the yosys interface with abc to send in all the lib? It's supported by yosys so there is no need to merge lib files
> 
> @arlpetergadfort I'm glad to abandon this PR if there is a better solution. What specifically are you suggesting?

@maliberty presumably this is to overcome the one liberty file at the abc calls below?
https://github.com/The-OpenROAD-Project/OpenLane/blob/8ad16ce75c753a8effaa92cd977d3a30c8cb4a40/scripts/yosys/synth.tcl#L293
https://github.com/The-OpenROAD-Project/OpenLane/blob/8ad16ce75c753a8effaa92cd977d3a30c8cb4a40/scripts/yosys/synth.tcl#L315

If you need to pass in additional liberty files just add `-liberty fileA -liberty fileB...` to the abc call to have abc read `fileA` and `fileB`. The interface used to no support this, but it's does now, so there is no need concatenate the liberty files.

2022-01-20 15:04 UTC, maliberty commented
@arlpetergadfort it is more indirect than that, it is the call from yosys to yosys-abc during:
12.1.1. Executing ABC.

So I have to convince yosys to pass the flag.

2022-01-20 15:08 UTC, arlpetergadfort commented
> @arlpetergadfort it is more indirect than that, it is the call from yosys to yosys-abc during: 12.1.1. Executing ABC.
> 
> So I have to convince yosys to pass the flag.

@maliberty The two lines I highlighted should have been the ones that call yosys-abc.  Maybe I'm missing something else, but the yosys / yosys-abc interface can pass multiple liberty files, so the merging step is should not be needed.

2022-01-20 18:45 UTC, maliberty commented
@arlpetergadfort dfflibmap appears to only take one .lib file as an argument to -liberty.

2022-01-20 19:36 UTC, arlpetergadfort commented
@maliberty I see, I don't have a good solution there, except to suggest it would be possible to separately specify the file for the DFFLIB (usually the same as the other libs, but here a separate file I assume).

2022-01-20 19:37 UTC, maliberty commented
@arlpetergadfort in asap7 there are multiple .lib.  I think all the flops are in one of them so we could have a separate variable for the ff lib.  I don't know if that is always true though.

2022-01-20 22:29 UTC, mithro commented
Probably worth seeing if you can get a change into Yosys to allow multiple options if abc supports it.

2022-01-20 22:31 UTC, maliberty commented
@mithro  abc doesn't support it in dfflibmap - I'm sure it could be fixed but I'm not going to spend time on it.

2022-01-25 15:02 UTC, closed without merging